name: Clear Sonarcloud

on: 
  pull_request:
    types: [closed]
    
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: "-s -u ${{ secrets.SONAR_TOKEN }}: -d project=salomaoluiz_BuyIt https://sonarcloud.io/api/project_pull_requests/list > pull.json"
    - name: Get variable
      id: variables
      run: |
        sonarID=$(echo """`jq '.pullRequests[] | select(.branch == "${{ github.head_ref }}") | .key' pull.json `""")
        echo "::set-output name=sonarPullRequestID::$sonarID"
    - name: curl
      uses: wei/curl@v1
      with:
        args: "-s -u ${{ secrets.SONAR_TOKEN }}: -d project=salomaoluiz_BuyIt -d pullRequest=${{ steps.variables.outputs.sonarPullRequestID }} https://sonarcloud.io/api/project_pull_requests/delete"